type = "StandardMaterial"
[material]
base_color_texture = "carpet_b.png"
normal_map_texture = "carpet_b_normal.png"
metallic_roughness_texture = "carpet_b_mr.png"
metallic = 1.0
perceptual_roughness = 1.0



