type = "StandardMaterial"
[material]
base_color_texture = "subway_tile.png"
normal_map_texture = "subway_tile_normal.png"
metallic_roughness_texture = "subway_tile_mr.png"
metallic = 1.0
perceptual_roughness = 1.0



