type = "StandardMaterial"
[material]
base_color_texture = "wallpaper_zigzag.png"
normal_map_texture = "wallpaper_zigzag_normal.png"
metallic_roughness_texture = "wallpaper_zigzag_mr.png"
metallic = 1.0
perceptual_roughness = 1.0



